# vendor/killerwolf/mcp-profiler-bundle/Resources/config/routes.yaml
mcp_profiler_message_receive:
    path: /mcp/message/{connectionId}
    controller: Killerwolf\MCPProfilerBundle\Controller\MCPMessageController::receiveMessageAction
    methods: [POST]
    requirements:
        connectionId: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' # UUID format

mcp_profiler_sse_stream:
    path: /sse
    controller: Killerwolf\MCPProfilerBundle\Controller\MCPSseController::streamAction
    methods: [GET]