services:
    # Default configuration for services in this bundle
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Make the MCPServerService public
    MCP\ServerBundle\Service\MCPServerService:
        arguments:
            - '@parameter_bag'
        public: true

    # Alias for the MCPServerService
    mcp_server:
        alias: MCP\ServerBundle\Service\MCPServerService
        public: true
        
    # Command for running the MCP server
    MCP\ServerBundle\Command\RunMCPServerCommand:
        arguments:
            - '@mcp_server'
        tags:
            - { name: 'console.command' }
            
    # Register the new ProfilerCommand
    MCP\ServerBundle\Command\ProfilerCommand:
        arguments:
            - '@profiler'
        tags:
            - { name: 'console.command' }
            
    # Register ProfilerGetByToken as a service with the Profiler and ParameterBag injected
    MCP\ServerBundle\Tools\ProfilerGetByTokenTool:
        arguments:
            - '@?profiler'
            - null
            - '@parameter_bag'
        public: true
        tags:
            - { name: 'mcp_server.tool' }
            
    # Register ProfilerListTool as a service with the Profiler and ParameterBag injected
    MCP\ServerBundle\Tools\ProfilerListTool:
        arguments:
            - '@?profiler'
            - null
            - '@parameter_bag'
        public: true
        tags:
            - { name: 'mcp_server.tool' }
            
    # Register ExampleTool as a service
    MCP\ServerBundle\Tools\ExampleTool:
        public: true
        tags:
            - { name: 'mcp_server.tool' }