services:
    # Default configuration for services in this bundle
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Define ToolAnalyzer service (relies on autowiring for its dependencies)
    PhpLlm\LlmChain\Chain\ToolBox\ToolAnalyzer: ~

    # Define the main MCP Server Service
    Killerwolf\MCPProfilerBundle\Service\MCPServerService:
        arguments:
            $toolAnalyzer: '@PhpLlm\LlmChain\Chain\ToolBox\ToolAnalyzer'
            $tools: !tagged_iterator mcp_server.tool
            $params: '@parameter_bag'
            $logger: '@?logger'

    # Alias for the MCPServerService
    mcp_server:
        alias: Killerwolf\MCPProfilerBundle\Service\MCPServerService

    # Command for running the MCP server
    Killerwolf\MCPProfilerBundle\Command\RunMCPServerCommand:
        arguments:
            - '@mcp_server'
        tags:
            - { name: 'console.command' }

    # Command for testing profiler access (Seems unrelated to MCP server itself)
    Killerwolf\MCPProfilerBundle\Command\ProfilerCommand:
        arguments:
            - '@?profiler' # Optional profiler injection
        tags:
            - { name: 'console.command' }

    # --- Tool Service Definitions ---

    Killerwolf\MCPProfilerBundle\Tools\ProfilerList:
        arguments:
            - '@?profiler'
            - null # Config argument (kept from original)
            - '@parameter_bag' # Kept, as constructor still accepts it
        tags:
            - { name: 'mcp_server.tool' }

    Killerwolf\MCPProfilerBundle\Tools\ProfilerGetAllCollectorByToken:
        arguments:
            - '@?profiler'
            - null # Config argument
        tags:
            - { name: 'mcp_server.tool' }

    Killerwolf\MCPProfilerBundle\Tools\ProfilerGetOneCollectorByToken:
        arguments:
            - '@?profiler'
            - null # Config argument
        tags:
            - { name: 'mcp_server.tool' }

    Killerwolf\MCPProfilerBundle\Tools\ProfilerGetByTokenTool:
        arguments:
            - '@?profiler'
            - null # Config argument
            - '@parameter_bag' # Kept, as constructor still accepts it
        tags:
            - { name: 'mcp_server.tool' }

    Killerwolf\MCPProfilerBundle\Tools\ExampleTool:
        tags:
            - { name: 'mcp_server.tool' }
