services:
    # Default configuration for services in this bundle
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Make the MCPServerService public
    Killerwolf\MCPProfilerBundle\Service\MCPServerService:
        arguments:
            - '@parameter_bag'
        public: true

    # Alias for the MCPServerService
    mcp_server:
        alias: Killerwolf\MCPProfilerBundle\Service\MCPServerService
        public: true
        
    # Command for running the MCP server
    Killerwolf\MCPProfilerBundle\Command\RunMCPServerCommand:
        arguments:
            - '@mcp_server'
        tags:
            - { name: 'console.command' }
            
    # Register the new ProfilerCommand
    Killerwolf\MCPProfilerBundle\Command\ProfilerCommand:
        arguments:
            - '@profiler'
        tags:
            - { name: 'console.command' }
            
    Killerwolf\MCPProfilerBundle\Tools\ProfilerList:
        arguments:
            - '@?profiler'
            - null
            - '@parameter_bag'
        public: true
        tags:
            - { name: 'mcp_server.tool' }
            
    Killerwolf\MCPProfilerBundle\Tools\ProfilerGetAllCollectorByToken:
        arguments:
            - '@?profiler'
            - null
            - '@parameter_bag'
        public: true
        tags:
            - { name: 'mcp_server.tool' }

    Killerwolf\MCPProfilerBundle\Tools\ProfilerGetOneCollectorByToken:
        arguments:
            - '@?profiler'
            - null
        public: true
        tags:
            - { name: 'mcp_server.tool' }
