services:
    # Default configuration for services in this bundle
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    # Create an alias for the Profiler class to the existing profiler service
    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

    # Command for running the MCP server
    Killerwolf\MCPProfilerBundle\Command\RunMCPServerCommand:
        arguments:
            - !tagged_iterator mcp.tool # Inject tools directly
        tags:
            - { name: 'console.command' }
        public: true # Keep public as it's used directly

    # Command for testing profiler access (Seems unrelated to MCP server itself)
    Killerwolf\MCPProfilerBundle\Command\ProfilerCommand:
        arguments:
            - '@?profiler' # Optional profiler injection
        tags:
            - { name: 'console.command' }
            
    # --- Tool Service Definitions ---

    Killerwolf\MCPProfilerBundle\Tools\ProfilerList:
        arguments:
            - '@?profiler'
            - null # Config argument (kept from original)
            - '@parameter_bag' # Kept, as constructor still accepts it
        tags:
            - { name: 'mcp.tool' }

    Killerwolf\MCPProfilerBundle\Tools\ProfilerGetAllCollectorByToken:
        arguments:
            - '@?profiler'
            - null # Config argument
        tags:
            - { name: 'mcp.tool' }

    Killerwolf\MCPProfilerBundle\Tools\ProfilerGetOneCollectorByToken:
        arguments:
            - '@?profiler'
            - null # Config argument
        tags:
            - { name: 'mcp.tool' }

    Killerwolf\MCPProfilerBundle\Tools\ProfilerGetByTokenTool:
        arguments:
            - '@?profiler'
            - null # Config argument
            - '@parameter_bag' # Kept, as constructor still accepts it
        tags:
            - { name: 'mcp.tool' }

    Killerwolf\MCPProfilerBundle\Tools\ExampleTool:
        tags:
            - { name: 'mcp.tool' }

